name: KServe
run-name: Create a PR to build KServe Image
on:
  workflow_dispatch:
    inputs:      
      target_branch:
        default: 'release-v0.11'
        description: 'Target Branch Name (e.g. release-v0.11, rhods-1.3x, etc.)'
        required: true
      gh_org:
        default: 'opendatahub-io'
        description: 'KServe GitHub Org'
        required: true
env:
  # GH_USER_EMAIL: 140449482+dsp-developers@users.noreply.github.com
  GH_USER_EMAIL: ljhiyh@gmail.com
  GH_USER_NAME: openshift-ai-serving-developers
  TARGET_BRANCH: ${{ inputs.target_branch }}
  TARGET_COMPONENT: kserve
  GH_ORG: ${{ inputs.gh_org }}
  CONFIG_TEMPLATE: "./.github/scripts/templates/config.yaml"

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: jooho/testA # jooho/kserve 리포지토리를 클론
        token: ${{ secrets.AI_SERVING_DEV_ACCESS_TOKEN}}
    
    - name: Generate branch name with date
      id: branch_name
      run: |
        # 현재 날짜를 YYYYMMDD 형식으로 가져옵니다.
        branch_date=$(date +'%Y%m%d')
        
        # 브랜치 이름을 생성합니다.
        branch_name="build-bot-$branch_date"
        
        # 출력 변수에 브랜치 이름을 저장합니다.
        # echo "::set-output name=branch::$branch_name"
        echo "branch={branch_name}" >> $GITHUB_STATE
      
    - name: Create and push changes
      run: |
        # 브랜치 이름을 가져옵니다.
        # branch_name="${{ steps.branch_name.outputs.branch }}"
        branch_name="{branch}" >> $GITHUB_OUTPUT
        
        # 새로운 브랜치를 만들고 a.txt 파일을 추가합니다.
        git checkout -b $branch_name
        echo "Hello, World" > a.txt
        git add a.txt
        git commit -m "Add a.txt"
        git push origin $branch_name

    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.JASON_GITHUB_TOKEN }}
        branch: build-bot
        base: main
        title: "Add a.txt"
        body: "This is a test PR to github.com/jason4849/testA"

    - name: Delete build-bot branch
      if: steps.create_pr.outputs.pull-request-number
      run: |
        cd testA # jooho/kserve 리포지토리로 이동
        git push origin --delete build-bot
